layer/environments/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = patterns('',
                       url(r'^upload_servers/$',
                           login_required(views.ServersUploadView.as_view()),
                           name='upload_new_servers'),
                       url(r'^fetch_servers_properties/$',
                           login_required(views.ServerPropertiesFetchView.as_view()),
                           name='fetch_server_properties'),
                       url(r'^layout/(?P<env_name>[A-Za-z0-9 ]+)/(?P<format>[A-Za-z0-9 ]+)/$',
                           views.EnvironmentLayoutView.as_view(),
                           name="html_layout"),
                       )

layer/measurements/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required

from . import views

urlpatterns = patterns('',
                       url(r'^$', views.MeasurementsManageView.as_view()),
                       url(r'^upload_client_metrics$',
                           login_required(views.ClientMetricsUploadView.as_view()),
                           name='upload_client_metrics_simple'),
                       url(r'^upload_cse_metrics$',
                           login_required(views.CSEMetricsUploadView.as_view()),
                           name='upload_client_metrics_cse'),
                       url(r'^upload_client_measurements$',
                           login_required(views.ClientMeasurementsUploadViewView.as_view()),
                           name='upload_client_measurements'),
                       url(r'^upload_server_metrics$',
                           login_required(views.ServerMetricsUploadView.as_view()),
                           name='upload_server_metrics_simple'),
                       url(r'^upload_server_measurements$',
                           login_required(views.ServerMeasurementsUploadViewView.as_view()),
                           name='upload_server_measurements_simple'),
                       url(r'^import_server_measurements_zabbix$',
                           login_required(views.ServerMeasurementsZabbixGetView.as_view()),
                           name='upload_server_measurements_zabbix'),
                       url(r'^import_server_metrics_zabbix$',
                           login_required(views.ServerMetricsZabbixGetView.as_view()),
                           name='upload_server_metrics_zabbix'),
                       url(r'^client/table/(?P<app_name>[A-Za-z0-9 ]+)/(?P<run_id>[0-9]+)/$',
                           views.ClientMeasurementsAppTableView.as_view(),
                           name='client_measurements_table'),
                       url(r'^client/excel_table/(?P<app_name>[A-Za-z0-9 ]+)/(?P<run_id>[0-9]+)/$',
                           views.ClientMeasurementsAppReportTableView.as_view(),
                           name='client_measurements_excel_table'),
                       url(r'^results/violations/(?P<run_id>[0-9]+)/$',
                           views.SLAViolationsStatTableView.as_view(),
                           name='sla_violations_table'),
                       url(r'^results/skipped/(?P<run_id>[0-9]+)/$',
                           views.SkippedTestCasesTableView.as_view(),
                           name='skipped_testcases_table'),
                       url(r'^results/client/(?P<metric_id>[0-9]+)/(?P<run_id>[0-9]+)/$',
                           views.ClientMeasurementsResultsView.as_view(),
                           name='client_side_json_results'),
                       url(r'^results/server/(?P<server_name>[A-Za-z0-9-]+)/(?P<metric_id>[0-9]+)/(?P<run_id>[0-9]+)/$',
                           views.ServerMeasurementsResultsView.as_view(),
                           name='server_side_json_results'),
                       url(r'^client/coverage_table/(?P<run_id>[0-9]+)/$',
                           views.TestCaseCoverageTableView.as_view(),
                           name='coverage_view'),
                       url(r'^client/cse_coverage_table/(?P<run_id>[0-9]+)/$',
                           views.CSETestCaseCoverageTableView.as_view(),
                           name='cse_coverage_view'),
                       url(r'^client/cse_new_cases_table/(?P<run_id>[0-9]+)/$',
                           views.CSENewTestCasesTableView.as_view(),
                           name='cse_new_cases_view'),
                       url(r'^client/load_profile_table/(?P<run_id>[0-9]+)/$',
                           views.LoadProfileTableView.as_view(),
                           name='load_profile_table'),
                       url(r'^server/metric/chart_settings/(?P<metric_id>[0-9]+)/$',
                           views.ServerMetricSimpleChartSettings.as_view(),
                           name='server_metric_chart_settings'),
                       url(r'^client/metric/chart_settings/(?P<metric_id>[0-9]+)/$',
                           views.ClientMetricSimpleChartSettings.as_view(),
                           name='client_metric_chart_settings'),
                       url(r'^server/metric_family/chart_settings/(?P<family>[A-Za-z0-9\/ ]+)/$',
                           views.ServerMetricFamilySimpleChartSettings.as_view(),
                           name='server_metric_family_chart_settings'),
                       url(r'^statistics/chart_settings/sla_violations/$',
                           views.RunsIssuesChartSettings.as_view(),
                           name='sla_violations_stats_chart_settings'),
                       url(r'^fill_test_cases/$',
                           login_required(views.FillTestCasesForRunView.as_view()),
                           name='fill_test_cases'),
                       url(r'^link_test_cases/$',
                           login_required(views.LinkMetricsWithTestCases.as_view()),
                           name='link_test_cases'),
                       url(r'^upload_perf_field_tests$',
                           login_required(views.PerfFieldReportUploadView.as_view()),
                           name='upload_perf_field_tests'),
                       url(r'^reset_cache$',
                           login_required(views.reset_cache),
                           name='reset_cache'),
                       )

layer/reports/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required, permission_required
from . import views
from measurements import views as meas_views

urlpatterns = patterns('',
                       url(r'^$', views.ProjectsListView.as_view()),
                       url(r'^(?P<project_name>[A-Za-z ]+)/$',
                           views.ProjectOverview.as_view(),
                           name='project_overview'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/needhelp/',
                           views.ProjectHelpView.as_view(),
                           name='project_help'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/stats/$',
                           views.ProjectStatsView.as_view(),
                           name='project_stats'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/stats/(?P<metric_id>[0-9]+)/$',
                           meas_views.ClientMeasurementsReleasesStatsView.as_view(),
                           name='client_stats_table'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/stats/sla_violations/$',
                           meas_views.RunsOffendersStatView.as_view(),
                           name='sla_violations_stats_table'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/search/suggest/$', # url parameters are implied for that view
                           views.FindTestsSuggestView.suggest_list_json,
                           name='search_tests_suggest'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/search/$', # url parameters are implied for that view
                           views.FoundTestsView.as_view(),
                           name='search_tests'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/(?P<section_name>[A-Za-z ]+)/$',
                           views.SectionOverview.as_view(),
                           name='section_overview'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/(?P<section_name>[A-Za-z ]+)/needhelp',
                           views.SectionHelpView.as_view(),
                           name='section_help'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/(?P<section_name>[A-Za-z ]+)/(?P<year>[0-9]{4})/$',
                           views.TestsListView.as_view(),
                           name='tests_list'),
                       url(r'^(?P<project_name>[A-Za-z ]+)/(?P<section_name>[A-Za-z ]+)/(?P<jira_key>[A-Z0-9-]+)/$',
                           views.TestDetailedView.as_view(),
                           name='test_report'),
                       url(r'^(?P<jira_key>[A-Z0-9-]+)/$',
                            views.TestShortURLRedirectView.as_view(),
                            name='test_redirect'),
                       url(r'^(?P<jira_key>[A-Z0-9-]+)/testplan$',
                            views.TestPlanShortURLRedirectView.as_view(),
                            name='test_plan_redirect'),
                       url(r'^(?P<jira_key>[A-Z0-9-]+)/(?P<attach_name>[A-Za-z0-9_\+\-\)\(\.]+)$',
                           views.TestAttachShortURLRedirectView.as_view(),
                           name='test_attach_redirect'),
                       url(r'^import_tests/$',
                           login_required(views.FillTestsView.as_view()),
                           name='import_tests'),
                       )

layer/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next "admin" lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
admin.site.index_template     = "admin/layer_index.html"
admin.site.app_index_template = "admin/layer_app_index.html"


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'layer.views.home', name='home'),
    # url(r'^layer/', include('layer.foo.urls')),

    url(r'^accounts/login/$',
        'django.contrib.auth.views.login',
        {'template_name': 'login.html'}),

    url(r'^' + settings.MEDIA_URL + r'(?P<path>.*)$',
        'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/',
        include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/',
        include(admin.site.urls)),

    url(r'^_measurements/',
        include('measurements.urls', namespace="measurements")),
    url(r'^_env/',
        include('environments.urls', namespace="environments")),

    url(r'^', include('reports.urls', namespace='reports'))
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

layer/apps/models.py
from django.db import models


class Vendor(models.Model):
    name = models.CharField(max_length=120)
    description = models.CharField(max_length=120)

    def __str__(self):
        return self.name


class App(models.Model):
    """ Application group is a group of application from one vendor
    and under same versioning
    """
    name = models.CharField(max_length=120, unique=True)
    description = models.CharField(max_length=1000, blank=True)
    vendor = models.ForeignKey(Vendor, null=True)

    def __str__(self):
        return self.name


class Component(models.Model):
    """Component is a logical part of application group"""
    name = models.CharField(max_length=60)
    description = models.CharField(max_length=120)
    app = models.ForeignKey(App)

    def __str__(self):
        return self.name


class Branch(models.Model):
    name = models.CharField(max_length=60)
    date_created = models.DateField()

    class Meta:
        verbose_name_plural = 'branches'
        ordering = ['-date_created']

    def __str__(self):
        return self.name


class Build(models.Model):
    version = models.CharField(max_length=60)
    build_date = models.DateField()
    branch = models.ForeignKey(Branch)
    app = models.ForeignKey(App)

    class Meta:
        ordering = ['-build_date', 'version']
        # There are can't be two identical versions in one application groups
        unique_together = ('version', 'app')

    def __str__(self):
        return self.version


class Release(models.Model):
    """Release is a set of builds of different apps groups

    Main build shows as release build
    """
    name = models.CharField(max_length=60)
    create_date = models.DateField()
    main_build = models.ForeignKey(Build, related_name='main_build')
    other_builds = models.ManyToManyField(Build, blank=True, null=True)

    def get_short_release_name(self):
        return '.'.join(self.main_build.version.split('.')[:2])

    def __str__(self):
        return self.name

layer/environments/models.py
import datetime

from django.db import models
from django.db.models import Q
from django.utils.timezone import utc


class HardwareEnvironment(models.Model):
    """Environment is a group of all-sufficient servers"""
    name = models.CharField(max_length=120, unique=True)
    description = models.TextField(blank=True, null=True)

    def get_actual_servers(self, timestamp=None):
        if timestamp is None:
            return Server.objects.filter(environment=self.id,
                                         decommission_timestamp=None)
        else:
            return Server.objects.filter(environment=self.id) \
                .filter(Q(decommission_timestamp=None) | Q(decommission_timestamp__gte=timestamp))

    def __str__(self):
        return self.name


class Server(models.Model):
    name = models.CharField(max_length=120)
    environment = models.ForeignKey(HardwareEnvironment)
    hosted_components = models.ManyToManyField('apps.Component', null=True, blank=True)
    role = models.CharField(max_length=120, null=True, blank=True)
    decommission_timestamp = models.DateTimeField(null=True, blank=True)

    class Meta:
        unique_together = (("name", "environment", "decommission_timestamp"),)
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_server_properties(self, timestamp=None):
        if timestamp is None:
            timestamp = datetime.datetime.utcnow().replace(tzinfo=utc)
        # PostgreSQL only
        return ServerProperty.objects.filter(server=self.id,
                                             timestamp__lte=timestamp)\
            .order_by('name', '-timestamp').distinct('name')

    def get_server_role(self):
        if self.role:
            return self.role
        else:
            try:
                role = ''.join(i for i in self.name.split('-')[2] if not i.isdigit()).upper()
            except IndexError:
                role = 'ALL'
            return role


class ServerProperty(models.Model):
    name = models.CharField(max_length=240)
    value = models.CharField(max_length=240)
    timestamp = models.DateTimeField()
    server = models.ForeignKey(Server)

    class Meta:
        verbose_name_plural = 'server properties'
        unique_together = (('name', 'timestamp', 'server'),)
        get_latest_by = 'timestamp'

    def __str__(self):
        return "%s=%s" % (self.name, self.value)


class ClientEnvironment(models.Model):
    name = models.CharField(max_length=120, unique=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

layer/environments/forms.py
from django import forms
from . import models


class ServersUploadForm(forms.Form):

    def __init__(self, servers_choices, *args, **kwargs):
        super(ServersUploadForm, self).__init__(*args, **kwargs)
        self.fields['environment'] = forms.ModelChoiceField(models.HardwareEnvironment.objects.all())
        self.fields['servers'] = forms.MultipleChoiceField(choices=servers_choices)


class ServerPropertiesFetchForm(forms.Form):
    cpu_cores = forms.CharField(max_length=120, initial='CPU number of cores')
    memory_bytes = forms.CharField(max_length=120, initial='Total memory')
    os_installed = forms.CharField(max_length=120, initial='Host information')
    servers = forms.ModelMultipleChoiceField(models.Server.objects.all())

layer/templates/_environment.html
<dt>Environment:</dt><dd style="padding-left: 200px;"><a href="{% url "environments:html_layout" env_name=object format="excel" %}">{{ object }} (Export all settings)</a></dd>
{% for role_name, role_configurations in roles.items %}
    <dt>{{ role_name }}:</dt>
    {% for configuration, qty in role_configurations.items %}
    <dd style="padding-left: 200px;">
        {{ qty }} server{{ qty|pluralize }}.
        {% for propertie_name, propertie_value in configuration %}
        {{ propertie_name }}:
        {% if 'bytes' in propertie_name %}{{ propertie_value|filesizeformat }}{% else %}{{propertie_value}}{%endif%}{% if not forloop.last %},{% else %}.{% endif %}
        {% endfor %}
    </dd>
    {% endfor %}
{% endfor %}

layer/templates/_table.html
{% load django_tables2 %}
    <a name="{{ title|slugify }}"></a>
    <h3>{{ title }}</h3>
 {% render_table table %}

layer/templates/measurements.html
{% extends "base.html" %}
{% load static %}
{% block extra_head %}<link rel="stylesheet" type="text/css" href="{% get_static_prefix %}styles/style.css" media="screen" />{% endblock %}
{% block title %}Upload{% endblock %}
{% block content %}
    <h1>Available measurements manage pages</h1><br><br>
    <div>
    <h1>File uploads</h1>
        <h2>Client Side</h2>
    <ul><a href="{% url 'measurements:upload_client_metrics_simple' %}">Upload client metrics from CSV file(simple uploader)</a> </ul>
    <ul><a href="{% url 'measurements:upload_client_metrics_cse' %}">Upload client metrics from CSE report</a> </ul>
    <ul><a href="{% url 'measurements:upload_client_measurements' %}">Upload client measurements results from CSV file(simple uploader)</a> </ul>
    <h2>Server Side</h2>
    <ul><a href="{% url 'measurements:upload_server_metrics_simple' %}">Upload server metrics from file</a> </ul>
    <ul><a href="{% url 'measurements:upload_server_measurements_simple' %}">Upload server measurements results from file</a> </ul>
    <br><br><br>
    <h1>External Uploads</h1>
    <ul><a href="{% url 'environments:upload_new_servers' %}">Upload new servers from zabbix</a> </ul>
    <ul><a href="{% url 'environments:fetch_server_properties' %}">Fetch server properties</a> </ul>
    <ul><a href="{% url 'measurements:upload_server_metrics_zabbix' %}">Import server metrics from zabbix</a> </ul>
    <ul><a href="{% url 'measurements:upload_server_measurements_zabbix' %}">Import server measurements from zabbix</a> </ul>
    <ul><a href="{% url 'measurements:fill_test_cases' %}">Fill run with test cases</a> </ul>
    <ul><a href="{% url 'measurements:link_test_cases' %}">Link run metrics with test cases</a> </ul>
    <ul><a href="{% url 'reports:import_tests' %}">Import tests from JIRA</a> </ul>
    <ul><a href="{% url 'measurements:upload_perf_field_tests' %}">Upload tests from Perf-Field report</a> </ul>
    </div>
{% endblock %}

layer/templates/report_default.html
{% extends 'report_base.html' %}
{% load static %}
{% load django_tables2 %}
{% block test_results %}
    {% if test.main_run.get_load_profile|length > 0 %}
    <div class="testResults">
        <h2>Coverage</h2>
        <div class="contentTable">
            <a hidden="true" href="{% url 'measurements:coverage_view' test.main_run.id %}"></a>
        </div>
    </div>

{% comment %}
    <div class="testResults">
        <h2>CSE Summary</h2>
        <div class="contentTable">
            <a hidden="true" href="{% url 'measurements:cse_coverage_view' test.main_run.id %}"></a>
        </div>
    </div>
{% endcomment %}

{#    <div class="testResults">#}
{#        <h2>CSE New Testcases</h2>#}
{#        <div class="contentTable">#}
{#            <a hidden="true" href="{% url 'measurements:cse_new_cases_view' test.main_run.id %}"></a>#}
{#        </div>#}
{#    </div>#}

    <div class="testResults">
            <h2>Skipped testcases</h2>
            <div class="contentTable">
                <a hidden="true" href="{% url 'measurements:skipped_testcases_table' test.main_run.id %}"></a>
            </div>
    </div>

    <div class="testResults">
        <h2>Load profile</h2>
        <div class="contentTable">
            <a hidden="true" href="{% url 'measurements:load_profile_table' test.main_run.id %}"></a>
        </div>
    </div>
    {% endif %}

    <div class="testResults">
    <h2>Server monitoring</h2>

    {% with participated_servers=test.get_servers_with_metrics %}
        {% regroup participated_servers|dictsort:"get_server_role" by get_server_role as server_roles %}
        {% for srv_role in server_roles %}
            <div class="graph">
                {% with server=srv_role.list.0 %}
                <div class="graph-heading">
                    <a name="Graphs-for-{{ srv_role.grouper }}"></a>
                    <h3>Graphs for {{ srv_role.grouper }}</h3>
                    <ul class="switcher"><li class="selected"><a>{{ server.name }}</a></li></ul>
                </div>
                <div class="graph-body">
                    <ul class="moduleList">
                        {% regroup server.get_available_metrics|dictsort:"get_family" by get_family as metrics_families_list %}
                        {% for metric_family in metrics_families_list %}
                        <li {% if forloop.first %}class="selected"{% endif %}>
                            <a href='#' settings='{{ metric_family.list.0.get_chart_settings_url |safe }}'
                               data='{ {% for metric in metric_family.list %}
                                        "{{ metric.id }}": "{{ metric.get_chart_data_url |safe }}" {% if not forloop.last %},{% endif %}
                                       {% endfor %} }'
                               type='line'>{{ metric_family.grouper }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="graphImg cropable">
                        <div class="chart-placeholder" style="width: 780px; height: 460px;"></div>
                    </div>
                </div>
                {% endwith %}
                <!-- graph-body -->
            </div> <!-- graph -->
        {% endfor %}
    {% endwith %}
    </div> <!-- testResults -->

    <div class="testResults">
        <h2>Response time statistics</h2>
        {% regroup test.main_run.get_load_profile by component as components %}
        {% for component in components %}
            <div class="contentTable">
                <a hidden="true" href="{% url 'measurements:client_measurements_table' component.grouper test.main_run.id %}{% if test.runs.all %}?additional_runs={% for addt_run in test.runs.all %}{{ addt_run.id }}{% if not forloop.last %},{% endif %}{% endfor %}{% endif %}"></a>
            </div>
        {% endfor %}
    </div>


    <div class="testResults">
        <h2>SLA violations</h2>
             <div class="contentTable">
                <a hidden="true" href="{% url 'measurements:sla_violations_table' test.main_run.id %}"></a>
            </div>
    </div>



     <div class="testResults">




                    {% with violations=test.main_run.get_sla_violations_metrics %}
                    {% if violations|length > 0 %}
                    <div class="graph">
                        <div class="graph-heading">
                            <a name="Graphs for methods with 95 percentile above SLA"></a>
                            <h3>Graphs for methods with 95 percentile above SLA</h3>
                        </div>
                        <div class="graph-body">
                            <ul class="moduleList">
                                {% for metric in violations %}
                                    {% if not metric.is_cse %}
                                    {% with client_metric=metric %}
                                        <li {% if forloop.first %}class="selected"{% endif %}>
                                             <a  href='#'
                                                settings='{% url "measurements:client_metric_chart_settings" metric_id=client_metric.id  %}'
                                                data='{

                                                "{{ metric.fgdfg }}": "{% url "measurements:client_side_json_results" metric_id=client_metric.id run_id=test.main_run.id %}"
                                              }'
                                                type='line'>
                                                {{ client_metric.name }}</a></li>
                                    {% endwith %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                            <div class="graphImg cropable">
                                <div class="chart-placeholder"style="width: 780px; height: 460px;"></div>
                            </div>
                        </div><!-- graph-body -->
                    </div> <!-
                        - graph -->
                    {% endif %}
                    {% endwith %}
        </div>



{#    <div class="testResults">#}
{#    <h2>Appendicies</h2>#}
{#    </div>#}
{% endblock %}

layer/templates/report_loaded_only.html
{% extends 'report_base.html' %}
{% load static %}
{% load django_tables2 %}
{% block test_results %}
    <div class="testResults">
        <h2>Coverage</h2>
        <div class="contentTable">
            <a hidden="true" href="{% url 'measurements:coverage_view' test.main_run.id %}"></a>
        </div>
    </div>

{% comment %}
    <div class="testResults">
        <h2>CSE Summary</h2>
        <div class="contentTable">
            <a hidden="true" href="{% url 'measurements:cse_coverage_view' test.main_run.id %}"></a>
        </div>
    </div>
{% endcomment %}

{#    <div class="testResults">#}
{#        <h2>CSE New Testcases</h2>#}
{#        <div class="contentTable">#}
{#            <a hidden="true" href="{% url 'measurements:cse_new_cases_view' test.main_run.id %}"></a>#}
{#        </div>#}
{#    </div>#}

    <div class="testResults">
        <h2>Load profile</h2>
        <div class="contentTable">
            <a hidden="true" href="{% url 'measurements:load_profile_table' test.main_run.id %}"></a>
        </div>
    </div>

    <div class="testResults">
    <h2>Server monitoring</h2>

    {% with participated_servers=test.main_run.get_loaded_servers %}
        {% regroup participated_servers|dictsort:"get_server_role" by get_server_role as server_roles %}
        {% for srv_role in server_roles %}
            <div class="graph">
                {% with server=srv_role.list.0 %}
                <div class="graph-heading">
                    <a name="Graphs for {{ srv_role.grouper }}"></a>

                    <h3>Graphs for {{ srv_role.grouper }}</h3>
                    <ul class="switcher"><li class="selected"><a>{{ server.name }}</a></li></ul>
                </div>
                <div class="graph-body">
                    <ul class="moduleList">
                        {% regroup server.available_metrics|dictsort:"get_family" by get_family as metrics_families_list %}
                        {% for metric_family in metrics_families_list %}
                        <li {% if forloop.first %}class="selected"{% endif %}>
                            <a href='#'
                               settings='{{ metric_family.list.0.get_chart_settings_url }}?server_id={{ server.id }}&run_id={{ test.main_run.id }}'
                               data='{
                                     {% for metric in metric_family.list %}
                                        "{{ metric.id }}": "{% url "measurements:server_side_json_results" server_name=server.name metric_id=metric.id run_id=test.main_run.id %}" {% if not forloop.last %},{% endif %}
                                     {% endfor %} }'
                               type='line'>
                                {{ metric_family.grouper }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    <div class="graphImg cropable">
                        <div class="chart-placeholder" style="width: 780px; height: 460px;"></div>
                    </div>
                </div>
                {% endwith %}
                <!-- graph-body -->
            </div> <!-- graph -->
        {% endfor %}
    {% endwith %}
    </div> <!-- testResults -->

    <div class="testResults">
        <h2>Response time statistics</h2>
        {% for component in test.section.components.all %}
            <div class="contentTable">
                <a hidden="true" href="{% url 'measurements:client_measurements_table' component test.main_run.id %}{% if test.runs.all %}?additional_runs={% for addt_run in test.runs.all %}{{ addt_run.id }}{% if not forloop.last %},{% endif %}{% endfor %}{% endif %}"></a>
                <a hidden="true" href="{% url 'measurements:client_measurements_excel_table' component test.main_run.id %}{%  querystring 'report-simplereportstattable'='xls' %}">Main run stats</a>
            </div>
        {% endfor %}
    </div>


    <div class="testResults">
        <h2>SLA violations</h2>
             <div class="contentTable">
                 <a hidden="true" href="{% url 'measurements:sla_violations_table' test.main_run.id %}"></a>
            </div>
    </div>



     <div class="testResults">






                    <div class="graph">
                        <div class="graph-heading">
                            <a name="Graphs for methods with 95 percentile above SLA"></a>
                            <h3>Graphs for methods with 95 percentile above SLA</h3>
                        </div>
                        <div class="graph-body">
                            <ul class="moduleList">
                                {% for metric in test.main_run.get_sla_violations_metrics %}
                                    {% if not metric.is_cse %}
                                    {% with client_metric=metric %}
                                        <li {% if forloop.first %}class="selected"{% endif %}>
                                             <a  href='#'
                                                settings='{% url "measurements:client_metric_chart_settings" metric_id=client_metric.id  %}'
                                                data='{

                                                "{{ metric.fgdfg }}": "{% url "measurements:client_side_json_results" metric_id=client_metric.id run_id=test.main_run.id %}"
                                              }'
                                                type='line'>
                                                {{ client_metric.name }}</a></li>
                                    {% endwith %}
                                    {% endif %}
                                {% endfor %}
                            </ul>
                            <div class="graphImg cropable">
                                <div class="chart-placeholder"style="width: 780px; height: 460px;"></div>
                            </div>
                        </div><!-- graph-body -->
                    </div> <!-- graph -->


        </div>



    <div class="testResults">
    <h2>Appendicies</h2>
    </div>
{% endblock %}